config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

  root to: 'devices#index'

  resources :devices, only: %i[edit update show] do
    get 'details', to: 'devices#details', on: :member
  end

  namespace 'charts' do
    scope '/:device_id' do
      get 'graph_stats'
    end
  end
end

app/models/aggregated_stat.rb
class AggregatedStat < ApplicationRecord
  belongs_to :device

  enum measurement: %i[humidity light temperature moisture]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
  has_many :stats, class_name: :DeviceStats, dependent: :destroy
  has_many :aggregated_stats, dependent: :destroy do
    def chart_data
      where(hour_at: (Time.now - 1.week)..Time.now).group_by_hour(:hour_at).average(:value).chart_json
    end
  end

  validates_presence_of :alias, :name

  broadcasts_to ->(_device) { :devices }, target: :devices

  def measurements
    stats.distinct.pluck(:measurement)
  end

  def humidity_stats
    stats.humidity
  end

  def light_stats
    stats.light
  end

  def temperature_stats
    stats.temperature
  end

  def moisture_stats
    stats.moisture
  end

  def aggregated(measurement)
    aggregated_stats.send(measurement)
  end

end

app/models/device_stats.rb
class DeviceStats < ApplicationRecord
  belongs_to :device

  enum measurement: %i[humidity light temperature moisture]

  after_create_commit do
    broadcast_replace_to :devices, target: "device_#{device.id}_last_#{measurement}", locals: { device: device, measurement: measurement }
  end

  def value=(val)
    write_attribute(:value, val.round(1))
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_device
  
  def graph_stats
    render json: @device.aggregated(params[:measurement]).chart_data
  end

  private

  def set_device
    @device = Device.find(params[:device_id])
  end

end

app/controllers/device_controller.rb
class DeviceController < ApplicationController
  def index
    @devices = Device.all
  end

  def edit
  end

  def update
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

  before_action :set_device, only: %i[show edit update details]

  def show
    render @device
  end

  def index
    @devices = Device.all
  end

  def edit; end

  def update
    if @device.update(params.require(:device).permit(:name))
      redirect_to @device
    else
      render :edit
    end
  end

  def details
  end

  private

  def set_device
    @device = Device.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/device_helper.rb
module DeviceHelper
end

app/views/device/index.html.erb
<h1>This are all your devices</h1>

<% @devices.each do |device| %>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">
        <%= link_to edit_device_path(device), class: 'text-decoration-none' do %>
          <%= device.alias %> <i class="bi bi-pencil"></i>
        <% end %>
      </h5>
      <div class="card-text">
        Humidity: <%= device.last_humidity %>
        Light: <%= device.last_light %>
      </div>
    </div>
  </div>
<% end %>

app/views/device_stats/_device_stats.html.erb
<%= turbo_frame_tag "device_#{device.id}_last_#{measurement}" do %>
  <% device_stat = device.send("#{measurement}_stats").last %>
  <% if device_stat.present? %>
    <h5><%= device_stat.measurement.capitalize %></h5>
    <p class="badge bg-light text-dark"><%= device_stat.value %>%</p>
    <div class="progress">
      <div class="progress-bar" role="progressbar" style="width: <%= device_stat.value %>%" aria-valuenow="<%= device_stat.value %>" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
  <% end %>
<% end %>

app/views/devices/_device.html.erb
<%= turbo_frame_tag dom_id(device) do %>
  <div class="card p-3 mb-2">
    <div>
      <%= turbo_frame_tag "device_#{device.id}_edit" do %>
        <div class="flex flex-row align-items-center justify-content-between">
          <div class="icon"><i class="bi bi-cpu" style="font-size: 2rem;"></i></div>
          <h4 class="mb-0">
            <%= device.name %>
            <%= link_to edit_device_path(device), class: 'card-link text-decoration-none' do %>
              <i class="bi bi-pencil"></i>
            <% end %>
          </h4>
        </div>
      <% end %>
    </div>
    <div class="mt-5">
      <% [:temperature, :light, :humidity, :moisture].each do |measurement| %>
        <%= render 'device_stats/device_stats', device: device, measurement: measurement %>
      <% end %>
    </div>
    <div class="mt-5">
      <%= link_to details_device_path(device), class: "card-link text-decoration-none", target: :_top do %>
        Details <i class="bi bi-clipboard-data"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/devices/_form.html.erb
<%= simple_form_for device do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>

  <%= f.button :submit, class: "btn-primary" %>
  <%= link_to 'Cancel', device, class: "btn btn-secondary" %>
<% end %>

app/views/devices/details.html.erb
<h1>Details</h1>
<%= link_to 'Home', root_path %>
<hr/>
<% [:moisture, :temperature, :light, :humidity].each do |measurement| %>
  <h2><%= measurement.capitalize %></h2>
  <%= area_chart charts_graph_stats_path(@device, measurement: measurement), ytitle: "Avg. #{measurement.capitalize}", refresh: 10, max: 100, min: 0 %>
<% end %>

app/views/devices/edit.html.erb
<%= turbo_frame_tag "device_#{@device.id}_edit" do %>
  <div data-controller='scroll-into-view' class='py-2'>
    <%= render 'form', device: @device %>
  </div>
<% end %>

app/views/devices/index.html.erb
<div class="mt-5">
  <h1>Earthchip dashboard</h1>
  <%= turbo_stream_from :devices %>
  <%= turbo_frame_tag :devices, class: "grid-wrapper mt-5 mb-3" do %>
    <%= render @devices %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Earthchip</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>